// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ProjectsRevealController from "./projects_reveal_controller"
application.register("projects-reveal", ProjectsRevealController)

import LineScrollController from "./line_scroll_controller"
application.register("line-scroll", LineScrollController)
